spring:
  config:
    import: env.properties
  datasource:
    url: jdbc:postgresql://localhost:5432/attendance
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss
application:
  name: Attendance management system
server:
  port: 8080
  servlet:
    context-path: /api/v1/